
import java.awt.Color;
import java.awt.Desktop;
import java.net.URL;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class CityAbout extends javax.swing.JFrame {

    /**
     * Creates new form About
     */
    public CityAbout() {
        initComponents();
        
        //to make texr areas not editable
        txtArea2.setEditable(false);
        txtArea3.setEditable(false);
        txtArea4.setEditable(false);
        txtArea5.setEditable(false);
        
        //to remove right side scroll bar of the text area
        jScrollPane2.setBorder(null);
        jScrollPane3.setBorder(null);
        jScrollPane4.setBorder(null);
        jScrollPane5.setBorder(null);
        
        //to remove the border of text area and add background color for text area
        txtArea2.setBorder(null);
        txtArea2.setBackground(new Color(153,153,153));
        
        txtArea3.setBorder(null);
        txtArea3.setBackground(new Color(153,153,153));
        
        txtArea4.setBorder(null);
        txtArea4.setBackground(new Color(153,153,153));
        
        txtArea5.setBorder(null);
        txtArea5.setBackground(new Color(153,153,153));
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtArea3 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtArea2 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtArea4 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtArea5 = new javax.swing.JTextArea();
        btnBack = new javax.swing.JButton();
        lblAccessBackButton = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnHistory = new javax.swing.JButton();
        btnClimate = new javax.swing.JButton();
        btnLanguage = new javax.swing.JButton();
        btnEconomy = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bernard MT Condensed", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText("ABOUT CARDIFF CITY");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 440, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel2.setText("History");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel3.setText("Climate");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        txtArea3.setColumns(20);
        txtArea3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtArea3.setRows(5);
        txtArea3.setText("Cardiff, in the north temperate zone, has a maritime climate marked by mild weather that is often cloudy, wet and windy. Summers tend to be warm and sunny, with average maxima between 19 and 22 °C (66 and 72 °F). Winters are fairly wet, but excessive rainfall as well as frost are rare. Spring and autumn feel similar and the temperatures tend to stay above 14 °C (57 °F) – also the average annual daytime temperature. Rain is unpredictable at any time of year, although showers tend to be shorter in summer.\n\nCardiff experiences less rainfall than average for Wales. It falls on 146 days in an average year, with total annual rainfall of 1,151.9 mm (45.35 in). Monthly rainfall patterns show that from October to January, average monthly rainfall in Cardiff exceeds 100 mm (3.9 in) each month, the wettest month being December with 125.3 mm (4.93 in) and the driest from April to June, with average monthly rainfall fairly consistent between 65 and 75 mm (2.6 and 3.0 in). Cardiff experiences lessrainfall than average for Wales. It falls on 146 days in an average year, with total annual rainfall of 1,151.9 mm (45.35 in). \n\nMonthly rainfall patterns show that from October to January, average monthly rainfall in Cardiff exceeds 100 mm (3.9 in) each month, the wettest month being December with 125.3 mm (4.93 in) and the driest from April to June, with average monthly rainfall fairly consistent between 65 and 75 mm (2.6 and 3.0 in).");
        jScrollPane2.setViewportView(txtArea3);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 1330, 100));

        txtArea2.setColumns(20);
        txtArea2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtArea2.setRows(5);
        txtArea2.setText("Archaeological evidence from sites in and around Cardiff show that people had settled in the area by at least around 6000 BC, during the early Neolithic; about 1,500 years before either Stonehenge or the Great Pyramid of Giza was completed.\n\nLittle is known of the fort and civilian settlement in the period between the Roman departure from Britain and the Norman Conquest. The settlement probably shrank in size and may even have been abandoned. In the absence of Roman rule, Wales was divided into small kingdoms Until the Roman conquest of Britain, Cardiff was part of the territory of the Silures – a Celtic. British tribe that flourished in the Iron Age.\n\nThe Senedd (Welsh Parliament; Welsh: Senedd Cymru) has been based in Cardiff Bay since its formation in 1999 as the \"National Assembly for Wales\". The Senedd building was opened on 1 March 2006 by The Queen.The Members of the Senedd (MSs), the Senedd Commission and ministerial support staff are based in Cardiff Bay.");
        jScrollPane3.setViewportView(txtArea2);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 1330, 100));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel4.setText("Language");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, -1, -1));

        txtArea4.setColumns(20);
        txtArea4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtArea4.setRows(5);
        txtArea4.setText("Cardiff has a chequered linguistic history with Welsh, English, Latin, Norse and Norman French preponderant at different times. Welsh was the majority language in Cardiff from the 13th century until the city's explosive growth in the Victorian era. As late as 1850, five of the 12 Anglican churches within the current city boundaries conducted their services exclusively in Welsh, while only two worshipped exclusively in English.\n\nThe city's first Welsh-language school (Ysgol Gymraeg Bryntaf) was established in the 1950s. Welsh has since regained ground. Aided by Welsh-medium education and migration from other parts of Wales, there are now many more Welsh speakers: their numbers doubled between the 1991 and 2011 censuses, from 18,071(6.6%) to 36,735 (11.1%) residents aged three years and above.\n\nIn addition to English and Welsh, the diversity of Cardiff's population (including foreign students) means that many other languages are spoken. One study has found that Cardiff has speakers of at least 94 languages, with Somali, Urdu, Bengali and Arabic being the most commonly spoken foreign ones.");
        jScrollPane4.setViewportView(txtArea4);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 1330, 100));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel5.setText("Economy");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, -1, -1));

        txtArea5.setColumns(20);
        txtArea5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtArea5.setRows(5);
        txtArea5.setText("As the capital city of Wales, Cardiff is the main engine of growth in the Welsh economy. Though the population of Cardiff is about 10% of the Welsh population, the economy of Cardiff makes up nearly 20% of Welsh GDP and 40% of the city's workforce are daily in-commuters from the surrounding South Wales area.\n\nCardiff today is the main finance and business services centre in Wales, with strong representation of finance and business services in the local economy. This sector, combined with the public administration, education and health sectors, have accounted for about 75% of Cardiff's economic growth since 1991. The city was recently placed seventh overall in the top 50 European cities in the fDI 2008 Cities of the Future list, and ranked seventh in terms of attracting foreign investment.\n\nCardiff is one of the most popular tourist destinations in the United Kingdom, receiving 18.3 million visitors in 2010 and generating £852 million for the city's economy. One result is that one in five employees in Cardiff is based in the distribution, hotels and restaurants sector, highlighting the growing retail and tourism industries in the city. The city has many hotels of varying sizes and standards, providing almost 9,000 available beds. Cardiff has several regeneration projects, such as St David's 2 Centre and surrounding areas of the city centre, and the £1.4 billion International Sports Village in Cardiff Bay, which played a part in the London 2012 Olympics. It features the only Olympic-standard swimming pool in Wales, the Cardiff International Pool, which opened on 12 January 2008. According to the Welsh Rugby Union, the Principality Stadium contributed £1 billion to the Welsh economy in the ten years after it opened in 1999, with around 85% of that staying in the Cardiff area.");
        jScrollPane5.setViewportView(txtArea5);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, 1330, 100));

        btnBack.setBackground(new java.awt.Color(153, 0, 0));
        btnBack.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("BACK");
        btnBack.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 5, true));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 730, 1370, 40));
        getContentPane().add(lblAccessBackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 20, 110, 20));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 51));
        jLabel7.setText("Cardiff is the capital and largest city of Wales. It forms a principal area, officially known as the City and County of Cardiff, and the city is the eleventh-largest in the UK.");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 1330, 20));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 51));
        jLabel8.setText("Located in the south-east of  Wales and in the Cardiff Capital Region. Cardiff is the county town of the historic county of Glamorgan and in 1974–1996 of South Glamorgan. ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 1360, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 51));
        jLabel9.setText("It belongs to the Eurocities network of the largest European cities.");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        btnHistory.setBackground(new java.awt.Color(0, 0, 51));
        btnHistory.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        btnHistory.setForeground(new java.awt.Color(255, 255, 255));
        btnHistory.setText("Want More Information About History ? CLICK HERE");
        btnHistory.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 51), 3, true));
        btnHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoryActionPerformed(evt);
            }
        });
        getContentPane().add(btnHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 370, 20));

        btnClimate.setBackground(new java.awt.Color(0, 0, 51));
        btnClimate.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        btnClimate.setForeground(new java.awt.Color(255, 255, 255));
        btnClimate.setText("Want More Information About Climate ? CLICK HERE");
        btnClimate.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 51), 3, true));
        btnClimate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClimateActionPerformed(evt);
            }
        });
        getContentPane().add(btnClimate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 370, 20));

        btnLanguage.setBackground(new java.awt.Color(0, 0, 51));
        btnLanguage.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        btnLanguage.setForeground(new java.awt.Color(255, 255, 255));
        btnLanguage.setText("Want More Information About Language ? CLICK HERE");
        btnLanguage.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 51), 3, true));
        btnLanguage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLanguageActionPerformed(evt);
            }
        });
        getContentPane().add(btnLanguage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, 370, 20));

        btnEconomy.setBackground(new java.awt.Color(0, 0, 51));
        btnEconomy.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        btnEconomy.setForeground(new java.awt.Color(255, 255, 255));
        btnEconomy.setText("Want More Information About Economy ? CLICK HERE");
        btnEconomy.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 51), 3, true));
        btnEconomy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEconomyActionPerformed(evt);
            }
        });
        getContentPane().add(btnEconomy, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 700, 370, 20));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HomeMenu8.jpg"))); // NOI18N
        jLabel6.setText("jLabel7");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        //Directing to Necessary windows when user pressed Back button
        
        //Creating variable BTNback to access the public lable variable declared
        //in each each interface
        String BTNback = lblAccessBackButton.getText();
        
        //if user came to the City About from Admin Menu, User will be directed to AdminMenu
                     //Accessing the lable value declared in Admin Menu
        if (BTNback == "AdminAbout") {
            
            dispose();
            Admin_Menu am= new Admin_Menu();
            am.setTitle ("Admin Menu");
            am.setVisible(true);
        }
        //if user came to the City About from Student Menu, User will be directed to StudentMenu
                     //Accessing the lable value declared in Student Menu
        else if (BTNback == "StudentAbout") {
            
            dispose();
            Student_Menu sm= new Student_Menu();
            sm.setTitle ("Student Menu");
            sm.setVisible(true);
        }
        //if user came to the City About from Tourist Menu, User will be directed to TouristMenu
                     //Accessing the lable value declared in Tourist Menu
        else if (BTNback == "TouristAbout") {
            
            dispose();
            Tourist_Menu tm= new Tourist_Menu();
            tm.setTitle ("Tourist Menu");
            tm.setVisible(true);
        } 
        //if user came to the City About from JbSeekerNbusinessmen Menu, User will be directed to JbSeekerNbusinessmen
                     //Accessing the lable value declared in JbSeekerNbusinessmen Menu
        else {

            dispose();
            JbSeekerNbusinessmen_Menu jsbm= new JbSeekerNbusinessmen_Menu();
            jsbm.setTitle ("JobSeekerNbusinessman Menu");
            jsbm.setVisible(true);
        }  
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoryActionPerformed
        // If user press History button, a web browser will be opened with the below website
        
        //Using try...catch block to catch if there's an exception
        try 
            {
                Desktop.getDesktop().browse(new URL("https://en.wikipedia.org/wiki/Cardiff#History").toURI());
            } 
            catch (Exception ex) 
            {
                System.out.println(""+ex);
            }
    }//GEN-LAST:event_btnHistoryActionPerformed

    private void btnClimateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClimateActionPerformed
        // If user press Climate button, a web browser will be opened with the below website
        
        //Using try...catch block to catch if there's an exception
        try 
            {
                Desktop.getDesktop().browse(new URL("https://en.wikipedia.org/wiki/Cardiff#Climate").toURI());
            } 
            catch (Exception ex) 
            {
                System.out.println(""+ex);
            }
    }//GEN-LAST:event_btnClimateActionPerformed

    private void btnLanguageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLanguageActionPerformed
        // If user press Language button, a web browser will be opened with the below website
        
        //Using try...catch block to catch if there's an exception
        try 
            {
                Desktop.getDesktop().browse(new URL("https://en.wikipedia.org/wiki/Cardiff#Language").toURI());
            } 
            catch (Exception ex) 
            {
                System.out.println(""+ex);
            }
    }//GEN-LAST:event_btnLanguageActionPerformed

    private void btnEconomyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEconomyActionPerformed
        // If user press Economy button, a web browser will be opened with the below website
        
        //Using try...catch block to catch if there's an exception
        try 
            {
                Desktop.getDesktop().browse(new URL("https://en.wikipedia.org/wiki/Cardiff#Economy").toURI());
            } 
            catch (Exception ex) 
            {
                System.out.println(""+ex);
            }
    }//GEN-LAST:event_btnEconomyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CityAbout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CityAbout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CityAbout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CityAbout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CityAbout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClimate;
    private javax.swing.JButton btnEconomy;
    private javax.swing.JButton btnHistory;
    private javax.swing.JButton btnLanguage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    public javax.swing.JLabel lblAccessBackButton;
    private javax.swing.JTextArea txtArea2;
    private javax.swing.JTextArea txtArea3;
    private javax.swing.JTextArea txtArea4;
    private javax.swing.JTextArea txtArea5;
    // End of variables declaration//GEN-END:variables
}
