
import java.awt.Desktop;
import java.net.URL;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class CityMap extends javax.swing.JFrame {

    /**
     * Creates new form CityMap
     */
    public CityMap() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAccessBackButton = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnCyncoed = new javax.swing.JButton();
        btnLandlaff = new javax.swing.JButton();
        btnRes = new javax.swing.JButton();
        btnBute = new javax.swing.JButton();
        btnPenylan = new javax.swing.JButton();
        btnStation = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(lblAccessBackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 30, 120, 20));

        btnBack.setBackground(new java.awt.Color(153, 0, 0));
        btnBack.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("BACK");
        btnBack.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 5, true));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 730, 1370, 40));

        btnCyncoed.setBackground(new java.awt.Color(0, 51, 51));
        btnCyncoed.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnCyncoed.setForeground(new java.awt.Color(0, 0, 51));
        btnCyncoed.setText("Cyncoed Campus");
        btnCyncoed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCyncoedActionPerformed(evt);
            }
        });
        getContentPane().add(btnCyncoed, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 270, -1, -1));

        btnLandlaff.setBackground(new java.awt.Color(0, 51, 51));
        btnLandlaff.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnLandlaff.setForeground(new java.awt.Color(0, 0, 51));
        btnLandlaff.setText("Cardiff Met Uni");
        btnLandlaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLandlaffActionPerformed(evt);
            }
        });
        getContentPane().add(btnLandlaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 400, -1, -1));

        btnRes.setBackground(new java.awt.Color(0, 51, 51));
        btnRes.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnRes.setForeground(new java.awt.Color(0, 0, 51));
        btnRes.setText("Harafs Resturant");
        btnRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResActionPerformed(evt);
            }
        });
        getContentPane().add(btnRes, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 520, -1, -1));

        btnBute.setBackground(new java.awt.Color(0, 51, 51));
        btnBute.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnBute.setForeground(new java.awt.Color(0, 0, 51));
        btnBute.setText("Bute Park");
        btnBute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnButeActionPerformed(evt);
            }
        });
        getContentPane().add(btnBute, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 560, -1, -1));

        btnPenylan.setBackground(new java.awt.Color(0, 51, 51));
        btnPenylan.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnPenylan.setForeground(new java.awt.Color(0, 0, 51));
        btnPenylan.setText("Penylan Surgery");
        btnPenylan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPenylanActionPerformed(evt);
            }
        });
        getContentPane().add(btnPenylan, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 380, -1, -1));

        btnStation.setBackground(new java.awt.Color(0, 51, 51));
        btnStation.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnStation.setForeground(new java.awt.Color(0, 0, 51));
        btnStation.setText("Cathays Station");
        btnStation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStationActionPerformed(evt);
            }
        });
        getContentPane().add(btnStation, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 440, 140, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CardiffMap.png"))); // NOI18N
        jLabel2.setDoubleBuffered(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 730));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        //Directing to Necessary windows when user pressed Back button
        
        //Creating variable BTNback to access the public lable variable declared
        //in each each interface
        
        String BTNback = lblAccessBackButton.getText();
        
        //if user came to the City Map from Admin Menu, User will be directed to AdminMenu
                     //Accessing the lable value declared in Admin Menu
        if (BTNback == "AdminMap") {
            
            dispose();
            Admin_Menu am= new Admin_Menu();
            am.setTitle ("Admin Menu");
            am.setVisible(true);
        }
        //if user came to the City Map from Student Menu, User will be directed to StudentMenu
                     //Accessing the lable value declared in Student Menu
        else if (BTNback == "StudentMap") {
            
            dispose();
            Student_Menu sm= new Student_Menu();
            sm.setTitle ("Student Menu");
            sm.setVisible(true);
        }
        //if user came to the City Map from Tourist Menu, User will be directed to TouristMenu
                     //Accessing the lable value declared in Tourist Menu
        else if (BTNback == "TouristMap") {
            
            dispose();
            Tourist_Menu tm= new Tourist_Menu();
            tm.setTitle ("Tourist Menu");
            tm.setVisible(true);
        } 
        //if user came to the City Map from JbSeekerNbusinessmen Menu, User will be directed to JbSeekerNbusinessmen
                     //Accessing the lable value declared in JbSeekerNbusinessmen Menu
        else {

            dispose();
            JbSeekerNbusinessmen_Menu jsbm= new JbSeekerNbusinessmen_Menu();
            jsbm.setTitle ("JobSeekerNbusinessman Menu");
            jsbm.setVisible(true);
        }  
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnLandlaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLandlaffActionPerformed
        // If user press btnLandlaff button, a web browser will be opened with the below website
        
        //Using try...catch block to catch if there's an exception        
        try 
            {
                Desktop.getDesktop().browse(new URL("https://www.google.com/maps/dir/51.482455,-3.1819754/cardiff+metropolitan+university/@51.4926266,-3.2149476,14z/data=!3m1!4b1!4m9!4m8!1m1!4e1!1m5!1m1!1s0x486e1cc7d35d3eef:0x5afe25c130d18e76!2m2!1d-3.2120517!2d51.4959559").toURI());
            } 
            catch (Exception ex) 
            {
                System.out.println(""+ex);
            }
    }//GEN-LAST:event_btnLandlaffActionPerformed

    private void btnStationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStationActionPerformed
        // If user press btnStation button, a web browser will be opened with the below website
        
        //Using try...catch block to catch if there's an exception 
        try 
            {
                Desktop.getDesktop().browse(new URL("https://www.google.com/maps/dir/51.482455,-3.1819754/cathays+station/@51.4850842,-3.1844636,16z/data=!3m1!4b1!4m9!4m8!1m1!4e1!1m5!1m1!1s0x486e1cbc68ec512b:0xc9431dbfde3da247!2m2!1d-3.1787399!2d51.4889067").toURI());
            } 
            catch (Exception ex) 
            {
                System.out.println(""+ex);
            }
    }//GEN-LAST:event_btnStationActionPerformed

    private void btnCyncoedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCyncoedActionPerformed
        // If user press btnCyncoed button, a web browser will be opened with the below website
        
        //Using try...catch block to catch if there's an exception 
        try 
            {
                Desktop.getDesktop().browse(new URL("https://www.google.com/maps/dir/51.482455,-3.1819754/cyncoed+campus/@51.4959246,-3.2048405,13z/data=!3m1!4b1!4m9!4m8!1m1!4e1!1m5!1m1!1s0x486e1cc7d35d3eef:0x72667e6577f6b23a!2m2!1d-3.1606436!2d51.5107704").toURI());
            } 
            catch (Exception ex) 
            {
                System.out.println(""+ex);
            }
    }//GEN-LAST:event_btnCyncoedActionPerformed

    private void btnPenylanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPenylanActionPerformed
        /// If user press btnPenylan button, a web browser will be opened with the below website
        
        //Using try...catch block to catch if there's an exception 
        try 
            {
                Desktop.getDesktop().browse(new URL("https://www.google.com/maps/dir/51.482455,-3.1819754/penylan+surgery/@51.4917386,-3.1875419,14z/data=!3m1!4b1!4m9!4m8!1m1!4e1!1m5!1m1!1s0x486e1ce970a0d16b:0x385acd0e4f32ec65!2m2!1d-3.1642275!2d51.4965509").toURI());
            } 
            catch (Exception ex) 
            {
                System.out.println(""+ex);
            }
    }//GEN-LAST:event_btnPenylanActionPerformed

    private void btnButeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnButeActionPerformed
        // If user press btnBute button, a web browser will be opened with the below website
        
        //Using try...catch block to catch if there's an exception 
        try 
            {
                Desktop.getDesktop().browse(new URL("https://www.google.com/maps/dir/51.482455,-3.1819754/bute+park+cardiff/@51.4833821,-3.1853134,17z/data=!3m1!4b1!4m9!4m8!1m1!4e1!1m5!1m1!1s0x486e1ca45662cb93:0x41e744e3c5cba3e6!2m2!1d-3.185252!2d51.4845766").toURI());
            } 
            catch (Exception ex) 
            {
                System.out.println(""+ex);
            }
    }//GEN-LAST:event_btnButeActionPerformed

    private void btnResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResActionPerformed
        // If user press btnRes button, a web browser will be opened with the below website
        
        //Using try...catch block to catch if there's an exception 
        try 
            {
                Desktop.getDesktop().browse(new URL("https://www.google.com/maps?rlst=f&rlz=1C1VDKB_enGB1028GB1028&lqi=Chlmb29kIHBsYWNlcyBpbiBncmFuZ2V0b3duSOHt2ZCLtoCACForEAAQARgAGAEiGWZvb2QgcGxhY2VzIGluIGdyYW5nZXRvd24qBggDEAAQAZIBCnJlc3RhdXJhbnSqAR0KCC9tLzAyd2JtEAEqDyILZm9vZCBwbGFjZXMoAA&vet=12ahUKEwjOsbfm68_7AhVPgFwKHfmWAkgQ8UF6BAgDEHA..i&lei=qB6EY869G8-A8gL5rYrABA&cs=1&um=1&ie=UTF-8&fb=1&gl=uk&sa=X&geocode=KX-DuZ48A25IMa3lN-fS_xFH&daddr=17+Corporation+Rd,+Cardiff+CF11+7AN").toURI());
            } 
            catch (Exception ex) 
            {
                System.out.println(""+ex);
            }  
    }//GEN-LAST:event_btnResActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CityMap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CityMap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CityMap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CityMap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CityMap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBute;
    private javax.swing.JButton btnCyncoed;
    private javax.swing.JButton btnLandlaff;
    private javax.swing.JButton btnPenylan;
    private javax.swing.JButton btnRes;
    private javax.swing.JButton btnStation;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel lblAccessBackButton;
    // End of variables declaration//GEN-END:variables
}
