/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() { 
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        buttonAdminLogin = new javax.swing.JButton();
        buttonOtherUserLogin = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel11.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1370, 769));
        setPreferredSize(new java.awt.Dimension(1370, 785));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonAdminLogin.setBackground(new java.awt.Color(0, 0, 51));
        buttonAdminLogin.setFont(new java.awt.Font("Bell MT", 1, 40)); // NOI18N
        buttonAdminLogin.setForeground(new java.awt.Color(255, 255, 255));
        buttonAdminLogin.setText("ADMIN");
        buttonAdminLogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 51), 5, true));
        buttonAdminLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAdminLoginActionPerformed(evt);
            }
        });
        getContentPane().add(buttonAdminLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 420, 350, 90));

        buttonOtherUserLogin.setBackground(new java.awt.Color(0, 51, 51));
        buttonOtherUserLogin.setFont(new java.awt.Font("Bell MT", 1, 40)); // NOI18N
        buttonOtherUserLogin.setForeground(new java.awt.Color(255, 255, 255));
        buttonOtherUserLogin.setText("OTHER USER");
        buttonOtherUserLogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 51), 5, true));
        buttonOtherUserLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOtherUserLoginActionPerformed(evt);
            }
        });
        getContentPane().add(buttonOtherUserLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 620, 350, 90));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Bernard MT Condensed", 3, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 51));
        jLabel8.setText("WELCOME TO CARDIFF CITY GUIDE ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/H3.jpg"))); // NOI18N
        jLabel13.setText("jLabel1");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 140, 370, 200));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/H2.jpg"))); // NOI18N
        jLabel14.setText("jLabel1");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 350, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/H1.jpg"))); // NOI18N
        jLabel15.setText("jLabel1");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 370, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/H5.jpg"))); // NOI18N
        jLabel16.setText("jLabel1");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 360, 370, 190));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/H7.jpg"))); // NOI18N
        jLabel17.setText("jLabel1");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 570, 370, 170));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/H4.png"))); // NOI18N
        jLabel18.setText("jLabel1");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 370, 190));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/H6.jpg"))); // NOI18N
        jLabel19.setText("jLabel1");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 570, 370, 170));

        jLabel3.setFont(new java.awt.Font("Bradley Hand ITC", 3, 14)); // NOI18N
        jLabel3.setText("A smart city that prioritises life, freedom, and equality rather than just technology.....");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HomeMenu2.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonOtherUserLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOtherUserLoginActionPerformed
        //Directing to Users_Login window when user pressed Other User button
        dispose();
        Users_Login bk= new Users_Login();
        bk.setTitle ( "Users Login");
        bk.setVisible(true);
    }//GEN-LAST:event_buttonOtherUserLoginActionPerformed

    private void buttonAdminLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAdminLoginActionPerformed
        //Directing to Users_Login window when user pressed Admin button
        dispose();
        Users_Login bk= new Users_Login();
        bk.setTitle ( "Users Login");
        bk.setVisible(true);
    }//GEN-LAST:event_buttonAdminLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdminLogin;
    private javax.swing.JButton buttonOtherUserLogin;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
