
import java.sql.Connection; //Provides the accessing and processing data stored in database
import java.sql.PreparedStatement;//Provides a feature to execute a parameterized query.
import java.sql.ResultSet;//a table of data representing a database result set, 
//which is usually generated by executing a statement that queries the database.
import javax.swing.JOptionPane;//used to provide standard dialog boxes

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class Users_Login extends javax.swing.JFrame {

    /** 
     * Creates new form Users_Login
     */
    Connection con;
    PreparedStatement ps;
    ResultSet rs;
            
    public Users_Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnUsersLogin = new javax.swing.JButton();
        btnRegisterUsers = new javax.swing.JButton();
        cmbUserType = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bernard MT Condensed", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText("           USER LOGIN !");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 21, 591, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 51));
        jLabel2.setText("USERNAME");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 238, -1, -1));

        txtUsername.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(576, 227, 378, 40));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 51));
        jLabel3.setText("PASSWORD");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 461, -1, -1));

        txtPassword.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(576, 450, 378, 40));

        btnUsersLogin.setBackground(new java.awt.Color(0, 0, 51));
        btnUsersLogin.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        btnUsersLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnUsersLogin.setText("LOGIN");
        btnUsersLogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 51), 5, true));
        btnUsersLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsersLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnUsersLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 680, 131, 60));

        btnRegisterUsers.setBackground(new java.awt.Color(0, 51, 51));
        btnRegisterUsers.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        btnRegisterUsers.setForeground(new java.awt.Color(255, 255, 255));
        btnRegisterUsers.setText("REGISTER");
        btnRegisterUsers.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 51), 5, true));
        btnRegisterUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterUsersActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegisterUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 680, 131, 60));

        cmbUserType.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cmbUserType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Admin", "Student", "Tourist", "JobSeeker", "Businessman" }));
        getContentPane().add(cmbUserType, new org.netbeans.lib.awtextra.AbsoluteConstraints(576, 336, 378, 40));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 51));
        jLabel4.setText("USER TYPE");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 347, -1, -1));

        btnBack.setBackground(new java.awt.Color(153, 0, 0));
        btnBack.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("BACK");
        btnBack.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 5, true));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 680, 118, 60));

        btnExit.setBackground(new java.awt.Color(153, 0, 0));
        btnExit.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("EXIT");
        btnExit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 5, true));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 680, 115, 60));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HomeMenu1.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUsersLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsersLoginActionPerformed
        
    //code for making log in allowed for all types of available users with their
    //username, password and User Type
    
        String uname = txtUsername.getText();
        String pswd = txtPassword.getText();
        String uType = cmbUserType.getSelectedItem().toString();
        
        //Checking for empty fields in the form
        if(txtUsername.getText().length()<=0 || txtPassword.getText().length()<=0 
                || uType.equals("Select"))
        {
        JOptionPane.showMessageDialog(null, "Fields can't be blank , Fill & Try "
                + "Again ! ", "Users Login", JOptionPane.WARNING_MESSAGE);
        } 
        else
        {
        //Using if....else statements inside a try..catch block to allow user 
        //to log in with the User Type
        try 
        {
            //Calling the dbConnection public method in dbConnection class
            con = dbConnection.getConnection();
            ps = con.prepareStatement("select * from login_reg_table where Username=? and Password=?");
            ps.setString(1, uname);
            ps.setString(2, pswd);
            rs = ps.executeQuery();

            if (rs.next()) 
            {
                String s1 = rs.getString("UserType");
                String un = rs.getString("Username");


                if(uType.equalsIgnoreCase("Admin") && s1.equalsIgnoreCase("admin"))
                {
                    dispose();
                    Admin_Menu am= new Admin_Menu(un);
                    am.setTitle ("Admin Menu");
                    am.setVisible(true);
                }
                else if(uType.equalsIgnoreCase("Student") && s1.equalsIgnoreCase("student"))
                {
                    dispose();
                    Student_Menu am= new Student_Menu(un);
                    am.setTitle ("Student Menu");
                    am.setVisible(true);
                }
                else if(uType.equalsIgnoreCase("Tourist") && s1.equalsIgnoreCase("tourist"))
                {
                    dispose();
                    Tourist_Menu am= new Tourist_Menu(un);
                    am.setTitle ("Tourist Menu");
                    am.setVisible(true);
                }
                else if(uType.equalsIgnoreCase("JobSeeker") && s1.equalsIgnoreCase("JobSeeker"))
                {
                    dispose();
                    JbSeekerNbusinessmen_Menu am= new JbSeekerNbusinessmen_Menu(un);
                    am.setTitle ("Job Seekers and Businessmen Menu");
                    am.setVisible(true);
                }
                else if(uType.equalsIgnoreCase("Businessman") && s1.equalsIgnoreCase("Businessman"))
                {
                    dispose();
                    JbSeekerNbusinessmen_Menu jbm= new JbSeekerNbusinessmen_Menu(un);
                    jbm.setTitle ("Job Seekers and Businessmen Menu");
                    jbm.setVisible(true);
                }
            }
            //Displaying a warning message when the user entered Username or 
            //Passwordn or User Type is incorrect
                else
                {
                  JOptionPane.showMessageDialog(null, "Incorrect Username , "
                  + "Password or User Type Entered!", "Users Login", JOptionPane.WARNING_MESSAGE);
                }
              
            } 
            
            catch (Exception ex) 
            {
                System.out.println(""+ex);
            }
        }
    }//GEN-LAST:event_btnUsersLoginActionPerformed

    private void btnRegisterUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterUsersActionPerformed
        // Using dispose to call dispose() on the frame, which will make it 
        //disappear and remove the resources it is using.
        dispose();
        //Directing to Users_Register window when user pressed Register button
        Users_Register ur= new Users_Register();
        ur.setTitle ( "Users Registration");
        //Making that window visible for user
        ur.setVisible(true);
    }//GEN-LAST:event_btnRegisterUsersActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        dispose();
        //Directing to Home window when user pressed Back button
        Home hm= new Home();
        hm.setTitle ( "Home");
        hm.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Users_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Users_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Users_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Users_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Users_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnRegisterUsers;
    private javax.swing.JButton btnUsersLogin;
    private javax.swing.JComboBox<String> cmbUserType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
